# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - HackAPI-V2

on:
  push:
    branches:
      - main
      - deploy-scripts
  workflow_dispatch:

env:
  SOLUTION: '**/*.sln'
  BUILDPLATFORM: 'Any CPU'
  BUILDCONFIGURATION: 'Release'
  AZURE_WEBAPP_NAME: 'hackapi-flrxxtaqbjtf2'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.301'
        include-prerelease: true

    - name: Build API
      run: dotnet build ./HackAPIs --configuration Release

    - name: Build DACPAC
      run: dotnet build ./NH4H_2021/NH4H_2021.sqlproj --configuration Release /p:NetCoreBuild=true /p:NETCoreTargetsPath=${{ github.workspace }}/NH4H_2021/BuildDirectory

    - name: create API artifact
      run: dotnet publish ./HackAPIs -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Upload API artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/myapp

    - name: Upload DB artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: database
        path: '**/*.dacpac'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Download API artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: .net-app
        path: ${{ github.workspace }}/webapp
    
    - name: Download database artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: database
        path: ${{ github.workspace }}/database
    
    - uses: Azure/sql-action@v1
      with:
        server-name: flrxxtaqbjtf2-hackdb-server.database.windows.net
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        dacpac-package: '**/*.dacpac'

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ./webapp

    - name: logout
      run: |
        az logout
